### PR TITLE
Add very vanilla home page listing recent reviews and popular streamers.

### PR DESCRIPTION
**Pull request by TravisWhitehead**
I started on the home page. Feedback is welcome (with both the code and the design itself). I kept it very simple and bootstrappy looking, so we can style it later.

[Here's a screenshot.](https://oregonstate.box.com/shared/static/w4e8k59biahi5eooq2shur13vf53j8zh.png)

I know the search bar wasn't in the design, I just threw it in to see what y'all think about it. Would be cool to have it just take us to the search for reviews page.

### CODE REVIEW

**Comment by KobaKiju** [comment]
Nice. Thanks for including the screenshot.

**Comment by KobaKiju** [comment]
I'll wait for Stephen to look at it before merging since you requested his review.

**Comment by TravisWhitehead** [comment]
It's no rush at the moment, just wanted to make you guys aware of it.

**Comment by Hoffmast1** [comment]
Niceee. You did a lot today.

**Pull request merged**
