### PR TITLE
Contact and about page

### PR DESCRIPTION
**Pull request by Hoffmast1**
everything works, expect for what needs to happen with the information
after it is submitted. As in where to store it or send it.

### CODE REVIEW

**Comment by Hoffmast1** [comment]
asfefafadsfds
Everything works and gives client side responses when not filling out form and hitting the submit button and what not.

**Comment by KobaKiju** [comment]
So the thing that's not there yet is the SQL code for storing the code from the text fields?

**Comment by KobaKiju** [comment]
I'm not entirely certain as to the purpose of this page. Is it meant to be a messaging service, or a means to contact the website admins?

**Comment by Hoffmast1** [comment]
Just a standard contact page, in the about us section we can write something at the end, like "Contact us if you have any issues with the site, or recommendations!"

**Comment by Hoffmast1** [comment]
We dont have to store it in a sql, we could just have it send an email, or some to a file locally.

**Pull request merged**
